
name: Build and Deploy Lennon

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
          cache: "pnpm"
      - run: "pnpm install"
      - run: "pnpm run build"
      - name: "select files for artifact"
        run: "mkdir artifact && mv dist prisma scripts package.json pnpm-lock.yaml artifact/"
      - name: "upload built files"
        uses: actions/upload-artifact@v3
        with:
          name: lennon
          path: "artifact"
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "get artifact download url"
        id: fetchurl
        run: |
          artifacts=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts);
          download_url=$(echo $artifacts | jq --raw-output '.artifacts[0].archive_download_url');
          echo "\n\n";
          echo "$artifacts";
          echo "$download_url";
          echo "::set-output name=url::$download_url";
        env:
          GH_TOKEN: ${{ github.token }}
      - name: "start deploy.sh on vps"
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sh lennon/scripts/deploy.sh ${{ github.token }} ${{ steps.fetchurl.outputs.url }}
          host: ${{ secrets.HOST }}
          username: github
          privateKey: ${{ secrets.PRIVATE_KEY }}
              